#!/bin/bash

test -z $1 && echo "Usage: cgroup-clean username
-- it creates cgroup named asai which can be freely modified by user asai"

rmdir -v /sys/fs/cgroup/*/$1/*/*/ | wc -l
rmdir -v /sys/fs/cgroup/*/$1/*/   | wc -l
