#!/bin/bash


usage (){
    cat >&2 <<EOF
 Usage: csv [DIRECTORIES...]
EOF
    exit 1
}

# while getopts ":f:t:" opt
# do
#     case ${opt} in
#         f) field=${OPTARG} ;;
#         t) type=${OPTARG} ;;
#         -) break;;
#         * ) echo "unsupported option $opt" ; usage ;;
#     esac
# done
# 
# shift $(($OPTIND - 1))

[ -z $1 ] && usage 
    
regex=$(find ${*:-"*"} -type d -links 2)

per_dir (){
    count=$(find $1 -name "*.plan*" | wc -l)
    echo "$(echo $1 | sed 's_[-/]_,_g'),$count"
}

export -f per_dir
export SHELL=/bin/bash

parallel per_dir ::: $regex
