#!/bin/bash

find $@ -name "*.qsub" | while read f
do
    out=${f%%qsub}*.out
    if ls $out &>/dev/null
    then
        if ! (grep -qs "Build date" $out)
        then
            echo $f
            echo "reason: lisp image not run" >&2
            continue
        fi
        if head -n 5 $out | grep -qs $(hostname)
        then
            echo $f
            echo "reason: somehow run on the server" >&2
            continue
        fi
        # if ( grep "Enhancing the problem" $out && ! grep "Solving the enhanced problem" $out ) &>/dev/null
        # then
        #     echo $f
        #     echo "reason: main search is not run under CAP configuration, terminated early" >&2
        #     continue
        # fi
        if grep -C 4 "parse error" $out >&2
        then
            echo $f
            echo "reason: FD detected a parse error" >&2
            continue
        fi
        if grep -C 4 "Usage error" $out >&2
        then
            echo $f
            echo "reason: FD detected a usage error" >&2
            continue
        fi
        
        plan=${f%%qsub}*.plan.1
        if [ -e $plan ]
        then
            if [ ! -r $plan ]
            then
                echo $f
                echo "reason: read flag off, not copied from the node" >&2
                continue
            fi
        fi
        err=${f%%qsub}*.err
        if ! ls $err &>/dev/null
        then
            echo $f
            echo "reason: no err file, problematic to the log parser" >&2
            continue
        elif grep -qs "No space left on device" $err
        then
            echo $f
            echo "reason: no space left on device, failed to write a translation results" >&2
            continue
        fi
    else
        echo $f
        echo "reason: no log files, job was not run" >&2
        continue
    fi
done

# ./notrun.sh results | xargs -n 1 dqsub $ipc 
