#!/bin/bash

find $@ -name "*.qsub" | while read f
do
    out=${f%%qsub}*.out
    if ls $out &>/dev/null
    then
        if ( grep "Enhancing the problem" $out && ! grep "Solving the enhanced problem" $out ) &>/dev/null
        then
            echo $f
            echo "reason: main search is not run under CAP configuration, terminated early" >&2
            continue
        fi
        if [ $(stat -c %Y $out) -le $(date -d "2015/08/22 15:00" +%s) ] \
            && grep "fun007" $out &>/dev/null
        then
            echo $f
            echo "reason: run on fun007 before memory change" >&2
            continue
        fi
        # mkdir=$(grep -c "mkdir: created directory" $out)
        # if [ $mkdir -lt 4 ]
        # then
        #     echo $f
        #     echo "reason: cgroup dir is not created 4 times: $mkdir" >&2
        #     continue
        # fi
        if grep -C 4 "parse error" $out >&2
        then
            echo $f
            echo "reason: FD detected a parse error" >&2
            continue
        fi
        if grep -C 4 "Usage error" $out >&2
        then
            echo $f
            echo "reason: FD detected a usage error" >&2
            continue
        fi
        
        plan=${f%%qsub}*.plan.1
        if [ -e $plan ]
        then
            if [ ! -r $plan ]
            then
                echo $f
                echo "reason: read flag off, not copied from the node" >&2
            fi
        fi

        
    else
        echo $f
        echo "reason: no log files, job was not run" >&2
    fi
done

# ./notrun.sh results | xargs -n 1 dqsub $ipc 
