#!/bin/bash

find $@ -name "*.qsub" | while read f
do
    out=${f%%qsub}*.out
    if ls $out &>/dev/null
    then
        if grep -C 4 "parse error" $out >&2
        then
            echo $f
            echo "reason: FD detected a parse error" >&2
            continue
        fi
        if grep -C 4 "Usage error" $out >&2
        then
            echo $f
            echo "reason: FD detected a usage error" >&2
            continue
        fi
        
        plan=${f%%qsub}*.plan.1
        if [ -e $plan ]
        then
            if [ ! -r $plan ]
            then
                echo $f
                echo "reason: read flag off, not copied from the node" >&2
            fi
        fi
        err=${f%%qsub}*.err
        if ls $err &>/dev/null
        then
            echo $f
            echo "reason: no err file, problematic to the log parser" >&2
        fi
        
    else
        echo $f
        echo "reason: no log files, job was not run" >&2
    fi
done

# ./notrun.sh results | xargs -n 1 dqsub $ipc 
