#!/bin/bash
# -*- mode:sh -*-

drop=~/Dropbox/component-planner/

greps=$(echo $@ | sed 's/ /|/g')

for d in $((ls -d results/* || exit 1) | grep -P "$greps")
do
    (
        ar="archives/$(basename $d).tar.gz"
        if [[ ( ! -e $ar ) || ( $d -nt $ar ) ]]
        then
            tar czf $ar $d
        fi
        cp -uv $ar $drop
    ) &
done

wait
