#!/bin/bash

min=${1:-1000}
nextrun=${2:-nextrun}

grep -v " *#" $nextrun

message (){
    echo "-------------------------------------------------------------"
    echo "Remaining experiments in $nextrun:"
    grep -v "#" $nextrun
    echo "^^^ Remaining experiments in $nextrun ^^^"
    date
    pwd
    echo " Refill when the # of jobs is below $min"
    echo "Last set of instances finished in $i minutes, $(grep -cv "#" $nextrun) lines remaining"
    echo "Expected completion time: $(date --date="$(($i*$(grep -cv "#" $nextrun))) min")"
}

i=0

message


while :
do
    n=$(qstat -B | awk '/Active/{print $4}')
    if (! [ -z $n ]) && [ $n -lt $min ]
    then
        $(dirname $(readlink -ef $0))/qsub-one-line $nextrun || break
        message $i
        i=0
    else
        echo sleep 60
        sleep 60
        i=$((i++))
    fi
done

echo "input line exhausted!"

