#!/bin/bash

min=${1:-1000}
nextrun=${2:-nextrun}

grep -v " *#" $nextrun

message (){
    echo "-------------------------------------------------------------"
    echo "Remaining experiments in $nextrun:"
    grep -v "#" $nextrun
    echo "^^^ Remaining experiments in $nextrun ^^^"
    date
    pwd
    echo " Refill when the # of jobs is below $min"
}

message

while :
do
    n=$(qstat -B | awk '/Active/{print $4}')
    if (! [ -z $n ]) && [ $n -lt $min ]
    then
        $(dirname $(readlink -ef $0))/qsub-one-line $nextrun || break
        message
    else
        echo sleep 60
        sleep 60
    fi
done

echo "input line exhausted!"

