#!/bin/bash

cmd=$($(dirname $(readlink -ef $0))/first-run-line $1)
echo $cmd
if [[ -z "$cmd" ]]
then
    exit 1
fi

eval $cmd
result=$?
cp $1 $1.old

comment-first-run-line < $1.old | tee $1

exit $result
