#!/bin/bash

min=${1:-10000}
nextrun=${2:-nextrun}

i=0
prev=0
next=0

print_refill (){
    echo "-------------------------------------------------------------"
    echo "Remaining experiments in $nextrun:"
    grep -v "#" $nextrun
    echo "^^^ Remaining experiments in $nextrun ^^^"
    date
    pwd
    echo " Refill when the # of jobs is below $min"
}

print_forecast (){
    echo "Last set of instances finished in $i minutes, $(grep -cv "#" $nextrun) lines remaining"
    echo "Expected completion time: $(date --date="$(($i*$(grep -cv "#" $nextrun))) min")"
}

print_refill

while :
do
    prev=$now
    now=$(qstat -B | awk '/Active/{print $4}')
    if (! [ -z $now ]) && [ $now -lt $min ]
    then
        $(dirname $(readlink -ef $0))/qsub-one-line $nextrun || break
        print_refill
        print_forecast
        i=0
    else
        echo "$(perl -e "print(($prev-$now)*60)") jobs / 1hr"
        sleep 60
        ((i++))
    fi
done

echo "input line exhausted!"

