#!/bin/bash

fd_log (){
    # Best solution cost so far: 111
    awk '/Best solution cost so far/{best=$6}END{print best}' $1
}

sum (){
    let result=0
    while read x ; do
        ! [ -z $x ] && ((result+=$x))
    done
    echo $result
}

summarize1 (){
    if $PRINT_TITLE
    then
        echo -n "${title:-$(basename $1)} "
    fi
    sum=$(find $1 -name "*.out" | while read line ; do ${parse:-fd_log} $line ; done | sum)
    echo $sum
}

summarize2 (){
    $PRINT_TITLE && echo -n "domain "
    echo $(basename $1)
    $PRINT_TITLE && echo -n "----- "
    echo -----
    { ls -d $1/*/ 2>/dev/null || exit 1 ; } | while read d ; do
        summarize1 $d
    done
    $PRINT_TITLE && echo -n "----- "
    echo -----
    title=total summarize1 $1
}


if [ -z $COLUMN ]
then
    COLUMN=true $0 $@ | column -t
else

    if ! [ -z $1 ]
    then
        d=$1
        shift

        if [ -z $PRINT_TITLE ]
        then
            paste <(PRINT_TITLE=true summarize2 $d) <(PRINT_TITLE=false $0 $@)
        else
            paste <(PRINT_TITLE=false summarize2 $d) <(PRINT_TITLE=false $0 $@)
        fi
    fi
fi

