#!/bin/bash

per_log (){
    # VALIDATE cost 0 111 
    # VALIDATE cost 1 111 
    sed 's///g' < $1 | awk '$4 ~ /^[0-9]+$/ && /VALIDATE/ {print $4}'  | sort | head -n 1
}

fd_log (){
    # Best solution cost so far: 111
    awk '/Best solution cost so far/{best=$6}END{print best}' $1
}

export -f per_log

sum (){
    let result=0
    while read x ; do
        ! [ -z $x ] && ((result+=$x))
    done
    echo $result
}

summarize1 (){
    if $PRINT_TITLE
    then
        echo -n "${title:-$(basename $1)} "
    fi
    sum=$(find $1 -name "*.log" | while read line ; do ${parse:-per_log} $line ; done | sum)
    echo $sum
}

summarize2 (){
    $PRINT_TITLE && echo -n "domain "
    echo $(basename $1)
    $PRINT_TITLE && echo -n "----- "
    echo -----
    { ls -d $1/*/ 2>/dev/null || exit 1 ; } | while read d ; do
        summarize1 $d
    done
    $PRINT_TITLE && echo -n "----- "
    echo -----
    title=total summarize1 $1
}


if [ -z $COLUMN ]
then
    COLUMN=true $0 $@ | column -t
else

    if ! [ -z $1 ]
    then
        d=$1
        shift

        if [ -z $PRINT_TITLE ]
        then
            paste <(PRINT_TITLE=true parse=fd_log summarize2 original2/fd900/) \
                <(PRINT_TITLE=false parse=fd_log summarize2 original2/fd1800/) \
                <(PRINT_TITLE=false summarize2 $d) <(PRINT_TITLE=false $0 $@)
        else
            paste <(PRINT_TITLE=false summarize2 $d) <(PRINT_TITLE=false $0 $@)
        fi
    fi
fi

