#!/bin/bash

export field=${field:-4}
export type=${type:-coverage}
export sortkey=${sortkey:-"-k 4"}

while getopts ":f:t:s:" opt
do
    case ${opt} in
        f) field=${OPTARG} ;;
        s) sortkey=${OPTARG} ;;
        t) type=${OPTARG} ;;
        -) break;;
        * ) echo "unsupported option $opt" ;;
    esac
done

shift $(($OPTIND - 1))

if [ -z $1 ]
then
    cat >&2 <<EOF
 Usage: quicksummary [-t coverage|plan] [DIRECTORIES...]

coverage : count the number of problems solved
plan     : count the number of plans found (possibly multiple plans per problem)

EOF
    exit 1
fi

cut_discriminating(){
    local words="$(cat)"
    local i=3
    while [ $i -lt 7 ]
    do
        if [ $(echo "$words" | cut -c 1-$i | wc -l) -eq $(echo "$words" | cut -c 1-$i | sort | uniq | wc -l) ]
        then
            break
        else
            ((i++))
        fi
    done
    echo "$words" | cut -c 1-$i
}
    
if [ -z $COLUMN ]
then
    COLUMN=true $0 $@ | column -t
else
    regex=$(ls -d ${*:-"*"} | LC_ALL=C sort -s -t- $sortkey)
    ptitle=
    title=
    for d in $regex
    do
        title=": cov $(echo $d/*/ | xargs -n 1 basename | sed 's/[aeiou]//g' | cut_discriminating | while read line ; do echo -n " $line "; done )"
        if [[ $ptitle != $title ]]
        then
            echo $title
            ptitle="$title"
        fi
        case $type in
            coverage)
                # ignore the last number
                count=$(find $d -name "*.plan*" | sed 's/\(.*\)\.[^.]*$/\1/g' | sort | uniq | wc -l) ;;
            plan)
                count=$(find $d -name "*.plan*" | wc -l) ;;
            *)
                echo "invalid type '$type' : should be one of : coverage, plan" >&2
                exit 1
        esac
        # count2=$(find $d -name "*.out" | xargs -n 1 grep "Solution found!" | wc -l)
        echo -n "$(basename $d | cut -d- -f $field) $count"
        #  $count2
        for dd in $d/*
        do
            count=$(find $dd -name "*.plan*" | wc -l)
            echo -n " $count"
        done
        echo
    done
fi
