#!/bin/bash

. $WORLD_HOME/template/common.sh

resource=$1
shift

if [[ $resource == "" || $@ == "" ]]
then
    cat <<EOF
Usage: run [resource-varname] [path...]
resource-varname : $resources (defined in in common.sh)
            path : directories where the qsub scripts are
EOF
    exit 1
fi

run=false


find $@ -path *.qsub | while read qsub ; do
    until dqsub $(ref $resource) $qsub
    do
        echo "retrying submission: dqsub $(ref $resource) $qsub"
        sleep 2
    done
done



