#!/bin/bash
# -*- mode : sh -*-
# usage: dqsub [-mMtTPd] -- command
# doubling-qsub

# echo "$0 $*"

. $WORLD_HOME/run/next.sh

mem=250000                   # 250MB
maxmem=2000000                  # 2GB: *8
time=225                     # 3.75 min = 30/4
maxtime=1800                    # 30 min
debug=false
queue=
nodes=1
ppn=1

while getopts ":p:n:q:u:g:m:M:t:T:d-" opt
do
    case ${opt} in
        q) queue=${OPTARG} ;;
        m) mem=${OPTARG:=$mem} ;;
        M) maxmem=${OPTARG:=$maxmem} ;;
        t) time=${OPTARG:=$time} ;;
        T) maxtime=${OPTARG:=$maxtime} ;;
        d) debug=true ;;
        -) break;;
        \?) OPT_ERROR=1; break;;
        * ) echo "unsupported option $opt" ;;
    esac
done

shift $(($OPTIND - 1))

if [[ -z $1 ]]
then
    cat <<EOF
Usage: 
       dqsub [-gpPqmMtTd] [--] job.qsub
EOF
    exit 1
fi

command=$(readlink -ef $1)
outname=$(basename $command .qsub)
dir=$(dirname $command)

################################################################ 

next
