#!/bin/bash

. common
config=${1:-~/.ssh/config}

trap "rm -vf $config.tmp" EXIT

while :
do
    host=$(./cfn-hostname $name)
    [ $? -ne 0 ] && break
    echo "Failed to find the public DNS" >&2
    sleep 5
done

echo "DNS found: $host" >&2

(
    sed "/^# BEGIN $name-cfn/,/^# END $name-cfn/d" < $config

    cat <<EOF
# BEGIN $name-cfn
Host $name
HostName $host
User $user
# END $name-cfn
EOF

) > $config.tmp

cat $config.tmp > $config
