#!/bin/bash -x

dir=$(dirname $(readlink -ef $0))

. $dir/common


name=${1:-$name}

if (cfncluster list | grep $name &>/dev/null)
then
    aws ec2 describe-instances --instance-ids \
        $(cfncluster instances $name | awk '/MasterServer/{print $2}') \
        | awk '$1 ~ /PublicDnsName/{print $2; exit}' \
        | sed 's/[",]//g'
else
    exit 1
fi

