#!/bin/bash

name=${1:-wasabi}
aws ec2 describe-instances --instance-ids \
    $(cfncluster instances $name | awk '{print $2}') \
    | grep PublicDnsName \
    | awk '{print $2}' \
    | head -n 1 \
    | sed 's/[",]//g'
